# Generated by Django 6.0.2 on 2026-02-28 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuspiciousKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Email", "Email"), ("SMS", "SMS"), ("Both", "Both")],
                        default="Both",
                        max_length=10,
                    ),
                ),
                ("weight", models.FloatField(default=10.0)),
            ],
        ),
        migrations.CreateModel(
            name="UrlChecked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000, unique=True)),
                ("checked_count", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Safe", "Safe"),
                            ("Suspicious", "Suspicious"),
                            ("High Risk", "High Risk"),
                        ],
                        default="Safe",
                        max_length=20,
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_analyzed", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Email", "Email"), ("SMS", "SMS"), ("URL", "URL")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("risk_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Safe", "Safe"),
                            ("Suspicious", "Suspicious"),
                            ("High Risk", "High Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("report_details", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_analyzed"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.analysisrecord",
                    ),
                ),
            ],
        ),
    ]
