# Generated by Django 6.0.2 on 2026-02-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("weight", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SafeDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="blacklistdomain",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="blacklistdomain",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blacklistdomain",
            name="risk_weight",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="suspiciouskeyword",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="suspiciouskeyword",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
